#pragma once

// Shared IOCTL codes.
#define IOCTL_WINSOCKRAW_BIND CTL_CODE(0x8000, 0x800, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_WINSOCKRAW_READ CTL_CODE(0x8000, 0x801, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_WINSOCKRAW_WRITE CTL_CODE(0x8000, 0x802, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

// Access flags.
#define SOCK_RAW_READ   (1 << 0)
#define SOCK_RAW_WRITE  (1 << 1)