#pragma once

// Device name.
#define WINSOCKRAW_DEVICE_NAME L"winsockraw"

// Interface index any.
#define WINSOCKRAW_INTERACE_ANY_INDEX   0xFFFFFFFF

// Shared IOCTL codes.
#define IOCTL_WINSOCKRAW_BIND CTL_CODE(0x8000, 0x800, METHOD_IN_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_WINSOCKRAW_READ CTL_CODE(0x8000, 0x801, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define IOCTL_WINSOCKRAW_WRITE CTL_CODE(0x8000, 0x802, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)